### ISSUE TITLE
Giving count privileges to a user (not admin) over a dataset at the Entity Class Permissions is resolving in an error in the Data Explorer

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#1918]
When I give count privileges to a USER (not admin) over 
- data explorer
- entity XYZ

Then I expect users to see data explorer and therein aggregates for XYZ
(without me needing to set permissions on xrefs or something)

Currently, I don't see anything unless I enable full view permissions.

**Comment by mswertz** [comment]
Indeed. this behave weird so lets fix

**Comment by dennishendriksen** [comment]
Cannot reproduce:
- Create non-super user
- Set dataexplorer view plugin permission to user
- Set settings_dataexplorer view entity permission and MolgenisUser count entity permission to user
- Logout, Login as user, Go to data explorer, select MolgenisUser

I now see the correct aggregation table.

**Comment by djvanenckevort** [comment]
The issue is that you need higher privileges (READ) on the XREF / MREF referenced entities. This issue still exists in v 1.8.2.

To reproduce:
1. Use an entity with an XREF or MREF to a different entity
2. Give a user count privileges to the entity
3. Access the entity in the data explorer

Actual result
Error! An error occurred. Please contact the administrator.
Message:No READ permission on entity <<XREF/MREF entity>>

**Comment by dennishendriksen** [comment]
Cannot reproduce in 1.17.0 snapshot

**Comment by Mark-de-Haan** [comment]
Also cannot reproduce, Suggest closing

**Comment by Mark-de-Haan** [comment]
Also cannot reproduce
