### ISSUE TITLE
Special characters not properly escaped in Model Registry

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2611]
Upload a VCF file and view the model details in the model registry.
Some characters (probably quotes) are shown as ? in the attribute tables

**Comment by Mark-de-Haan** [comment]
I had the same problem with the editor on the main page. We store the special characters as is in the database. Problem is that these special characters can not be rendered nicely by Java so they add a '?'. Fix is to use Html4Escape before storing the values so that a '<' is translated to the HTML named entity equivalent.

**Comment by fdlk** [comment]
I don't even see the vcf in the model registry.
Can you give a specific vcf to reproduce?

**Comment by mswertz** [comment]
Please fix and add to the EMX import documentation what characters are supported/escaped

**Comment by fdlk** [comment]
but data values are not shown in the model registry, I think?

**Comment by dennishendriksen** [comment]
How to reproduce?

**Comment by tommydeboer** [comment]
You can reproduce it by viewing the VCF *model* details, not the details of the VCF entity. 

![image](https://cloud.githubusercontent.com/assets/5362890/10814033/4119294e-7e23-11e5-9f82-971277ae2d77.png)
