### ISSUE TITLE
Creating a redirect plugin in the menumanager with a URL does not work

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#2736]
## Tested on: Molgenis01, Chrome ##

- Go to the menu manager
- Create a new redirect plugin with the query string: http://www.nu.nl and save
- Click the created plugin

Expected: We go to the nu.nl website
Result: We get a status 400 error, the url that was created is <host>/menu/main/redirect?http://www.nu.nl

**Comment by bartcharbon** [comment]
This is not a bug, in an url you need to specify both the key and the value for a parameter...
so it should be: Create a new redirect plugin with the query string: url=http://www.nu.nl and save

However if you do it correctly it still won't work, due to things added after the url: http://www.nu.nl/?plugin_id=redirect&footerText=null&authenticated=true&pluginid_with_query_string=redirect%3Furl%3Dhttp%3A%2F%2Fwww.nu.nl%2F&environment=production&app_top_logo=&app_home_logo=%2Fimg%2Flogo_molgenis_small.png
