### ISSUE TITLE
Clicking a row in the MREF select dropdown does not clear the input

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3059]
# Reproduce:

Upload TypeTest dataset.
Open filters.
In xmref_value, type lab
In the dropdown, click a row

## Expected:
The text in the select is cleared

## Actual:
The text in the select remains equal to "lab", no matter how many rows you select, until you close the dropdown.
![screen shot 2015-05-22 at 14 15 11](https://cloud.githubusercontent.com/assets/1523838/7770277/fdf1d6c0-008c-11e5-91c2-b25edf4a423f.png)

**Comment by fdlk** [comment]
Keep running into this, it's very annoying

**Comment by fdlk** [comment]
Talked with Bart and apperantly this is deliberate, feature requested by palga. It is inconsistent behavior with the new react EntitySelectBox (which I personally prefer).
To adapt the filters to create the same behavior as the EntitySelectBox, set 			`closeOnSelect: true` in jquery.molgenis.xrefmrefsearch.js line 133.

The other way around looks to be harder, since each row clicked triggers two new renders.

**Comment by mswertz** [comment]
ok, lets check with David what the the motivation is because unless there
is a good argument I like to move to the new react box behavior.

On Wed, Jun 3, 2015 at 8:40 PM, Fleur Kelpin <notifications@github.com>
wrote:

> Talked with Bart and apperantly this is deliberate, feature requested by
> palga. It is inconsistent behavior with the new react EntitySelectBox
> (which I personally prefer).
> To adapt the filters to create the same behavior as the EntitySelectBox,
> set closeOnSelect: true in jquery.molgenis.xrefmrefsearch.js line 133.
>
> The other way around looks to be harder, since each row clicked triggers
> two new renders.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3059#issuecomment-108568621>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by Mark-de-Haan** [comment]
This is now fixed
