### ISSUE TITLE
User editor shows "big fixme: password type"

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3061]
![screen shot 2015-05-22 at 15 18 30](https://cloud.githubusercontent.com/assets/1523838/7771196/dea1b836-0095-11e5-94da-b383a3ba9179.png)

(Did I just find the easter egg?)

**Comment by dennishendriksen** [comment]
This is the attribute description as described in /molgenis-security/src/main/resources/model/security.xml:
<field name="password_" label="Password" type="string" description="big fixme: password type"/>

**Comment by fdlk** [comment]
how should this behave then, should the description simpy be changed or should password fields have a second confirmation field?

**Comment by mswertz** [comment]
The description should be changed. Because this message is not helpful for
users.

Then this issue can be changed to 'User registration should show two
password fields to ensure password is correctly typed'

On Fri, May 29, 2015 at 1:15 PM, Fleur Kelpin <notifications@github.com>
wrote:

> how should this behave then, should the description simpy be changed or
> should password fields have a second confirmation field?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3061#issuecomment-106777173>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by fdlk** [comment]
User registration does already show this, and the account editor where you edit your own account as well, it's the admin's MolgenisUser editor screen that does not show this.

**Comment by mswertz** [comment]
Thanks :)

On Sat, May 30, 2015 at 10:02 AM, Fleur Kelpin <notifications@github.com>
wrote:

> User registration does already show this, and the account editor where you
> edit your own account as well, it's the admin's MolgenisUser editor screen
> that does not show this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3061#issuecomment-107006403>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by dennishendriksen** [comment]
This fix does not update existing MOLGENIS instances since the meta data generated from the XML is only persisted once.

**Comment by fdlk** [comment]
Good point, I've created an issue to update all JPA metadata upon migration
