### ISSUE TITLE
JPA metadata changes are not detected when upgrading to a new version of molgenis

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3149]

**Comment by mswertz** [comment]
should this be implemented in a specific migration script (i.e. each time a JPA entity is changed) or has this to do with a generic migration of metadata?

**Comment by fdlk** [comment]
Apps can specify JPA entities in .xml files, so we cannot migrate them for them if large changes are executed. We have run a migration script once to import the metadata for JPA entities to the metadata repositories (entities/attributes). But now if a JPA entity gets updated, be it a system entity or otherwise, the changes don't make it to the metadata repositories.

I'd think that upon each startup of molgenis, changes in all JPA metadata should be written to the entities table. If we change our own JPA system entities so dramatically that data needs migrating, then yes, a specific change script is called for to migrate the old data.

**Comment by mswertz** [comment]
Or get rid of JPA? Do we really need it (because EMX also allows casting to
POJOs)?

On Wed, Jul 1, 2015 at 6:58 PM, Fleur Kelpin <notifications@github.com>
wrote:

> Apps can specify JPA entities in .xml files, so we cannot migrate them for
> them if large changes are executed. We have run a migration script once to
> import the metadata for JPA entities to the metadata repositories
> (entities/attributes). But now if a JPA entity gets updated, be it a system
> entity or otherwise, the changes don't make it to the metadata repositories.
>
> I'd think that upon each startup of molgenis, changes in all JPA metadata
> should be written to the entities table. If we change our own JPA system
> entities so dramatically that data needs migrating, then yes, a specific
> change script is called for to migrate the old data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/molgenis/molgenis/issues/3149#issuecomment-117751201>.
>



-- 
Dr. Morris A. Swertz
Coordinator BBMRI-NL common services for IT
Coordinator DTL sector health
Coordinator NFU biobank catalogue working group
Head Section Systems Genetics & Genomics Coordination Center
Associate Professor - Big data in biomedicine

Dept. of Genetics, CB50
University Medical Center Groningen
P.O. Box 30001
9700 RB  GRONINGEN
The Netherlands

Phone +31 50 3617100
Fax + 31 50 3617230
Email m.a.swertz@rug.nl

**Comment by bartcharbon** [comment]
JPA has been removed
