### ISSUE TITLE
Importing an entity with the same name but different casing will result in a locked importer

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3368]
## Reproduce
- Upload an EMX containing the entity Gender
- Upload an EMX containing the entity gender
## Expected

FAIL with good error message: there is already a entity with name 'Gender' that conflicts with 'gender'
(while our front-end is case-sensitive, our backend may not be hence we are strict in entity/attribute name checking).
## Observed

Importer is locked
Entity gender already exists
Entity Gender is unknown
Entity gender already exists
Entity Gender is unknown

and it goes on and on...

Looks like the part that checks if an entity exists is not case sensitive, and the part that wants to get the entity is case sensitive.

**Comment by fdlk** [comment]
The attempted solution fails cause it refuses to add rows to already imported entities.

Suggested solutions:

1. Make EMX case-insensitive

2. Use technical names in mysql backend
Don't expose this implementation detail to the outside, but do allow coexistence of a repository named Genes and one named genes through clever generation/administration of table names for repository names. (Shouldn't be needed to migrate since the current names are all valid and unique.) Added benefit would be that you can use longer entity names and attribute names.

Both will take more than just the .5 point that we have for this bugfix. Shall we make a story?

**Comment by dennishendriksen** [comment]
See http://www.molgenis.org/ticket/3746

**Comment by dennishendriksen** [comment]
Solved in 2.0:
- Lowercase [emx_lowercase.xlsx](https://github.com/molgenis/molgenis/files/616456/emx_lowercase.xlsx)
- Uppercase [emx_uppercase.xlsx](https://github.com/molgenis/molgenis/files/616457/emx_uppercase.xlsx)
PostgreSQL is case sensitive.
