### ISSUE TITLE
Api v2 attribute update fails

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#3908]
POST
URL: http://molgenis62.target.rug.nl/api/v2/org_molgenis_test_TypeTest/xdatetime
BODY: 
{entities:[{id:55, xdatetime: "2015-01-05T08:30:00+0200"}, {id:57, xdatetime: "2015-01-07T08:30:00+0200"}]}

Expected: after update xdatetime is 2015-01-05T08:30:00+0200
Observed: xdatetime is 2015-01-07T00:00:00+0100

![screen shot 2015-10-14 at 09 31 17](https://cloud.githubusercontent.com/assets/116559/10477501/f0ca691c-7256-11e5-9049-c8d4cabdd132.png)
![screen shot 2015-10-14 at 09 29 23](https://cloud.githubusercontent.com/assets/116559/10477510/002b5402-7257-11e5-9568-93c3ed8746d0.png)

**Comment by fdlk** [comment]
Same happens in api v1 when you update single attribute 
PUT `"1985-08-12T01:02:03+0200”` to `http://localhost:8080/api/v1/org_molgenis_test_TypeTest/1/xdatetime`

And the result will be `"1985-08-12T00:00:00+0200"`

**Comment by fdlk** [comment]
Mark and I extensively debugged:

The REST API's gson deserializer correctly deserializes to a `java.util.Date` value that includes the time component.

`DefaultEntity#get('xdatetime')` looks at the attribute type to determine what getter to call.

```
			case DATE_TIME:
				return getDate(attributeName);
```

`getDate('xdatetime')` returns a `java.sql.Date` with its internal long value still corretly set to the correct date+time value. But the JDBC driver interprets `java.sql.Date`s as dates with no time and updates the database value to the date only, with 00:00:00 UTC time.

The elasticsearch repository decorator subsequently interprets the java.sql.Date as a java.util.Date when serializing the Entity to a source document and writes the date+time values to the index.

So up to 1.11 the index masked that the underlying mysql value was incorrect. Since 1.11 the value is retrieved from mysql and shows that the time part is missing.
