### ISSUE TITLE
The base package is not filtered out of the list of packages shown in the Model Registry

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3986]
## Reproduce

Go to the Model registry
## Expected

I do not see the base package (as it says so in the test plan)
## Observed

I do see the base package

**Comment by dennishendriksen** [comment]
Selecting 'View Model Details' for the 'base' package results in a 'Error! An error occurred. Please contact the administrator.' message due to a 500 internal server error retrieving the tree data. Likely cause is a server timeout, since the server is still performing database queries when the error is displayed.

**Comment by dennishendriksen** [comment]
Updated the test plan: the observed behavior is now the expected behavior.
