### ISSUE TITLE
DAS throws bad argumentException when letter chromosome provided

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis#4124]
The embedding of the genome browser in custom entity reports, as described here: https://github.com/molgenis/molgenis/wiki/Custom-entity-report is not usable in practice. For chromosomes other than 1 through 22, such as X, Y or MT, the DAS service throws an error. This results in the custom entity report not showing at all. Therefore, for most genomic datasets, it cannot be enabled in its current state. Exceptions thrown:

```
ERROR u.a.e.mydas.controller.MydasServlet - BadCommandArgumentsException thrown
uk.ac.ebi.mydas.exceptions.BadCommandArgumentsException: Expecting at least one reference in the query string, but found nothing.
	at uk.ac.ebi.mydas.controller.DasCommandManager.featuresCommand(DasCommandManager.java:633) ~[mydas-1.6.7.jar:1.6.7]
WARN:oejs.ServletHandler:qtp302105334-839: /das/molgenis/dasdataset_ccgg/features
org.molgenis.data.UnknownAttributeException: 
	at org.molgenis.data.elasticsearch.request.QueryGenerator.getAttribute(QueryGenerator.java:749)
	at org.molgenis.data.elasticsearch.request.QueryGenerator.createQueryClause(QueryGenerator.java:175)
```

**Comment by bartcharbon** [comment]
Looked briefly into this last sprint:
I could not reproduce this with X or Y, an other problem occurred for those letters in the freemarker template provided by Joeri. Template tries to interpret X or Y as a variable rather that a letter/string value.

Might be that this error is specific for MT (For the record: MT means Mitochondrial DNA), makes sense since not all systems recognise this as a chromosome)

**Comment by bartcharbon** [comment]
cannot be reproduced if DAS is queried directly:
https://molgenis01.target.rug.nl/das/molgenis/dasdataset_test_entity/features?segment=MT:9680112,10004830;maxbins=2890

So it seems the fault originates from the translation from the entity report to the DAS query

**Comment by bartcharbon** [comment]
Cannot reproduce the original error (BadCommandArgumentsException).
I put single quotes around the CHROM in the freemarker template and now it works fine for X and Y.
MT looks a bit weird because the genome browser has nothing to show (results in a browser with empty tracks and/or error messages in the tracks)
