### ISSUE TITLE
Filter on full name Ontology_OntologyTerm results in multiple results

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#4248]
Go to DataExplorer: select entity entities
Add filter to fullName column: Ontology_OntologyTerm

Result: 
Ontology_OntologyTerm
Ontology_Ontology
Ontology_OntologyTermSynonym
Ontology_OntologyTermDynamicAnnotation
Ontology_OntologyTermNodePath

Expected: only Ontology_OntologyTerm row

**Comment by bartcharbon** [comment]
This is related to the issue with the values with a pipe in the value. The string and text filters perform a search rather than a exact match. Because the terms are splitted on the underscore all the entities with "Ontology" in the name are matched.

I propose to pool together all those issues, and solve those with one "fix the search behaviour" story. (I think one is in the backlog already)

**Comment by jjettenn** [comment]
Sounds good

**Comment by mswertz** [comment]
I can't find the story in MOLGENIS backlog. Can you please look @bartcharbon ?
Also, to prioritize this I would like to know what users/use cases will fail and do those cases happen often?

**Comment by dennishendriksen** [comment]
The observed behavior is the expected behavior, MOLGENIS performs a text search instead of an exact match search when filtering on string attributes.
