### ISSUE TITLE
Menu overlaps top of page content

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4413]
If the screen is narrower than the menu, but wider than the threshold for the hamburger button to appear, it becomes two (possibly more?) lines high.
But the page content doesn't scroll down, and gets hidden by the second line of the menu.
The top of the page becomes invisible and unreachable.

**Comment by mswertz** [comment]
what resolution is that?

**Comment by fdlk** [comment]
It depends on the menu, but for standard menus this got worse by the introduction of the language select box into the menu.

Currently on molgenis01 happens for widths between 768 and 1127 pixels.

@Mark-de-Haan I suspect this is one of the reasons why the selenium tests are failing.

**Comment by JanTimmermans** [comment]
@fdlk @mswertz @Mark-de-Haan 
I think that the problems are caused by the threshold for collapsing the menu.
768px is the default threshold of bootstrap for collapsing the menu.

I've have successfully tried to change this value by adding some lines to the molgenis.css.

Could you please discuss the desired implementation?

So far I thought of the following solutions:
1) Add lines to css with the default value. An admin only has to change the value if it needs to be changed. This could be further explained in the manual.
2) Change the css via a form field in the menu manager. For the user this could be a more convenient solution, but it could be very hard to implement as it requires writing to the core-ui css at run time.

For now, I would suggest to go for the first solution [PR #4684](https://github.com/molgenis/molgenis/pull/4684)
