### ISSUE TITLE
If I copy my entity when annotating and the annotation fails, the created entity is not removed

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4510]
## Reproduce
- Import the following file:
[test_no_samples_2.vcf.zip](https://github.com/molgenis/molgenis/files/132729/test_no_samples_2.vcf.zip)

- Annotate with SnpEff and check the create copy checkbox
- Annotation fails

## Expected
-  The copied entity is removed

## Observed
- The copied entity still exists, but contains 0 additional information

**Comment by tommydeboer** [comment]
There is not an easy or clean solution for this because the annotator framework does not (and shouldn't) know it is annotating a copy. 

A better solution would be to add a 'clone' button in the data explorer, and not offer the copy option in the annotator tab anymore.

@mswertz how would you like us to proceed?

**Comment by fdlk** [comment]
But the annotator controller surely knows if it's annotating a copy or not?

**Comment by Mark-de-Haan** [comment]
The controller knows it is creating a copy yes

**Comment by tommydeboer** [comment]
The controller knows, but the job doesn't. Since it's asynchronous, you don't have that information available when the job fails.

**Comment by jjettenn** [comment]
PR: Fix #4510 sprint82
