### ISSUE TITLE
When adding general items in a specific entityreport, changes also happen in the general table

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5273]
#### Reproduce

![screen shot 2016-09-20 at 14 36 06](https://cloud.githubusercontent.com/assets/10075439/18670734/925f62e4-7f41-11e6-9da0-9a0255242b70.png)
![screen shot 2016-09-20 at 14 36 27](https://cloud.githubusercontent.com/assets/10075439/18670736/92607e2c-7f41-11e6-8426-8219a5e2f654.png)
First the table opens normally, but when clicking the entity report:
![screen shot 2016-09-20 at 14 36 35](https://cloud.githubusercontent.com/assets/10075439/18670733/925f4412-7f41-11e6-9cb1-0f3ededf3c8f.png)
![screen shot 2016-09-20 at 14 36 43](https://cloud.githubusercontent.com/assets/10075439/18670735/925fca40-7f41-11e6-876f-bc9b74f94ae7.png)

Observed in chrome with molgenis 1.22
#### Expected

Only the specific entity report should change
#### Observed

The whole data table changes color

**Comment by fdlk** [comment]
I'm not sure I agree with the expected behavior (but happy to be convinced :) )
The jquery selector explicitly selects all table rows on the entire page.
You can easily rewrite it to select only table rows in a specific div with id or class:

`$('#divId .table.table-striped tr').addClass('info')` or `$('.specific-class.table.table-striped tr').addClass('info')`
