### ISSUE TITLE
Confusing error message when deleting entity that's refEntity of mref

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5494]
#### Reproduce
As admin:
Upload [FDP-5.xlsx](https://github.com/molgenis/molgenis/files/578601/FDP-5.xlsx)

Open fdp_Catalog entity, press "Delete data + metadata"

#### Expected
Error message explains that Metadata.contains references Catalog

#### Observed
> Error! Cannot delete entity 'fdp_Metadata_contains' because entity 'fdp_Catalog' depends on it.

**Comment by dennishendriksen** [comment]
Currently a constraint violation is detected by PostgreSQL trying to delete the junction table for the Metadata.contains attribute. The PostgreSQL exception is then translated in ```PostgreSqlException.translateDependentObjectsStillExist```.

In order to produce a better error message we should map PostgreSQL table names to entity names (or labels?) and attribute names (or labels?) and produce an error message based on the mapping.

**Comment by marikaris** [comment]
In 5.1 I get: Error! Cannot delete entity 'fdp_Catalog' because entity 'fdp_Metadata' depends on it. Pretty clear I guess
