### ISSUE TITLE
When updating enum options on an existing model I do not get an error and my options are not updated

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5500]
#### Reproduce
I uploaded a model with an enum in it with certain options. I added an option and uploaded again with add/update. I did not get an error and my enum options were also not updated. 

#### Expected
I expect to get an error if adding enum options through updating is not supported or to have my enum options updated 

#### Observed
Nothing happens except from an import success.

**Comment by dennishendriksen** [comment]
Fixed in 2.0:
Importing [emx_5500-add.xlsx](https://github.com/molgenis/molgenis/files/623804/emx_5500-add.xlsx) in add mode followed by importing [emx_5500-update.xlsx](https://github.com/molgenis/molgenis/files/623806/emx_5500-update.xlsx) in add/update mode results in the following error: ```Error! Your import failed:
You are trying to upload entities that are not compatible with the already existing entities: [base_enum5500]```

Note that even though the EMX importer doesn't allow metadata updates, you can easily edit the enumOptions of an Attribute through the Data explorer plugin.
