### ISSUE TITLE
Update attribute sequence number and the row in the Data Explorer disappears

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#5528]
#### Reproduce
LOAD: TypeTest
Go to: Data Explorer -> Attribute (Entity)
Use the search box type: xbool
Update the sequence number to a new one (example: 1000)
Create

#### Expected
To see the same rows as before the update

#### Observed
No rows

**Comment by tommydeboer** [comment]
The problem is that after the update the UI immediately does a new search query. But because the attribute hasn't been indexed yet, you get zero results. 

As a patch I let queries that go to the index wait for the index to be stable (with a one second time-out). However, that wasn't enough because the indexing of an attribute takes about 4 seconds (on my machine). We decided against a higher time-out because that will cause many idle threads when there are many index queries.

Proposed solution is to keep searching in the old indexed entity while the new version is being prepared, and then swap them instantaneously when its ready.

**Comment by Mark-de-Haan** [comment]
Was [fixed](https://github.com/tommydeboer/molgenis/commit/e77c2b70a39b9380928c339199cccf96f7703bd2)
