### ISSUE TITLE
JavaScript date return value cannot be converted

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5824]
### How to Reproduce
load a dataset with a date as string in it, map it to a model which requires a date

### Expected behavior
I can map my string to an actual date using Date.parse() or Date.UTC() (of course using the right format, but even a copy of the ISO 8601 docs ("1994-11-05T08:15:30-05:00") in Date.parse does not result in a valid date. 

### Observed behavior
Error! (I think the function does not exist, it also gets slightly greyer than existing functions like Date.now())

**Comment by fdlk** [comment]
I would expect Date.parse to turn the string into a JavaScript Date. Then you need to turn that Date into a Number by calling getTime() on it. If that no longer works, it's a bug. If something simpler used to work, it worked because entity had more lenient attribute setters in 1.x and it's intended behavior that this no longer works.
