### ISSUE TITLE
REST API v2 RSQL query value not encoded

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5833]
### How to Reproduce
- Use [TypeTest](https://github.com/molgenis/molgenis/files/787188/it_emx_datatypes.xlsx) to filter 
- Filter on datetime

### Expected behavior
Filter is applied

### Observed behavior
Error, the server responded with a status of 400 (Bad Request)

**Comment by dennishendriksen** [comment]
The URL produced to retrieve filtered data changed from ```/api/v2/it_emx_datatypes_TypeTest?q=xdatetime%3Dge%3D2017-02-23T09%3A56%3A11%2B0100``` to ```/api/v2/it_emx_datatypes_TypeTest?q=xdatetime=ge=2017-02-23T09:56:11+0100``` due to changes in #5807 which fixes #5805.

When decoding the URL Spring replaces the plus character with a space which results in binding errors, see https://jira.spring.io/browse/SPR-11047. Since plus is reserved character per https://tools.ietf.org/html/rfc3986#section-2.2 it should be escaped.
