### ISSUE TITLE
register on demo server

### ISSUE THREAD

**Issue by KrisRousseau** [molgenis/molgenis#6294]
I would like to test molgenis on your demo server (molgenis.org/demo). I have to fill-in a username and a password but I did not find anywhere to register.

Could you tell me how I could connect to this demo web site ?

Best regards.

**Comment by marikaris** [comment]
Hi there! Due to malicious users we turned off the sign up for a while. I turned it on for now so you can sign up. However I turned moderation on, so probably when you register we have to accept it.

Another alternative: are you familiar with docker? We have a molgenis repository for this: https://github.com/molgenis/docker
It is easy to set up and try it out for yourself, even if you haven't used docker before.

**Comment by marikaris** [comment]
I created an account which seems to be working
