### ISSUE TITLE
Can't delete package for complex EMX

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6365]
### How to Reproduce
Import [emx_model.xlsx](https://github.com/molgenis/molgenis/files/1135675/emx_model.xlsx)
Go to dataexplorer
Go to Package table
Delete row for eu_bbmri_eric package

### Expected behavior
Package and all entity types are deleted

### Observed behavior
`Error! Value 'eu_bbmri_eric_collections' for attribute 'id' is referenced by entity 'sys_md_Attribute'.`

**Comment by tommydeboer** [comment]
Because of the long package + entity names, the technical identifiers for reference tables get truncated and are therefore different from the main table:

**eu_bbmri_eric_collections**#4dc0234e6
**eu_bbmri_eric_collecti**#4dc023e6*_age_unit*
**eu_bbmri_eric_collecti**#4dc023e6*_contact*
*etc.*

I think these tables aren't deleted properly and I suspect this issue is highly related to #6325 so I'm picking them both up.
