### ISSUE TITLE
MOLGENIS mail settings user name and password required by forget password

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis#6516]
### How to Reproduce
- Configure MOLGENIS Mail settings without username or password (e.g. using local MTA on localhost)
- Logout
- Click on "Sign in"
- Click on "Forgot password"
- Fill in your e-mail address and click on "Reset password"

### Expected behavior
- Password reset e-mail is sent

### Observed behavior
- I receive the following message: 
"Error! Cannot create mail sender. Username or password of the mail account not specified in the system mail settings."

**Comment by tommydeboer** [comment]
@djvanenckevort I'm not sure I understand. Without configuring the mail settings it's not possible to send e-mails.

**Comment by djvanenckevort** [comment]
Not all mail servers require a username & password. It is common to have an MTA on localhost that accepts mail from localhost without authentication.

**Comment by fdlk** [comment]
I think it is not so much a bug in the code but a bug in the specs that I thought up when building this. Should be pretty straightforward to fix. Only pitfall is the validity check at boot time. Server picks up defaults from property file at boot time and tries to send mail at boot time. Refuses to boot if mail settings in property file are incorrect. Boots fine if no username/password specified. 

Should now somehow learn to distinguish between the two cases
* empty properties present in properties file configuring local host mta which is down => refuse to boot to warn the synopsis that configured mail is broken?
* no properties present => boot with inconfigured mail so that mail settings can be configured by admin through the web interface?

**Comment by djvanenckevort** [comment]
I think the code for picking up the properties is not the problem. I can set MOLGENIS mail properties without a username / password and it validates as well. Only when trying to do a password reset I get the above mentioned error message. I think that the password reset does an check on the properties that is not necessary / not in the right place.

Anyway I would think that you would always want MOLGENIS to start up even if the MTA is down. Otherwise it gets difficult to fix things if you need fixing the settings in MOLGENIS.

**Comment by fdlk** [comment]
Exactly! If the values in the property file are incorrect, how will the admin find out?

**Comment by djvanenckevort** [comment]
I would say that you put up an error banner with details in the web interface somehow if an admin is logged in. For other users you would only put up a banner with a message that mail is not available where that functionality is required (e.g. password reset and feedback).

**Comment by mswertz** [comment]
send email to admin ... oh wait ;-)

**Comment by tommydeboer** [comment]
This fix removed the error message so it's possible to configure a mail server without a username/password. 

@djvanenckevort @fdlk What to do with the discussion above? Can we morph it into a story?
