### ISSUE TITLE
RSQL complex ref filter is incorrectly applied and shown in Data Explorer

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#6689]
### How to Reproduce
1. Import *it_emx_datatypes*
2. **<your_molgenis>**/menu/main/dataexplorer?entity=it_emx_datatypes_TypeTest&mod=data&filter=((xmref_value==ref1,xmref_value==ref3),(xmref_value==ref3;(xmref_value==ref4,xmref_value==ref5)))

### Expected behavior
The Data Explorer filter says:
```xmref_value: (('label1' or 'label3') and ('label3')) or ('label4' or 'label5')```

### Observed behavior
The Data Explorer filter says:
```
xmref_value: (('label1' or 'label3') and ('label3') or ('label4' or 'label5')
                                                   ^ missing )
```

**Comment by marikaris** [comment]
The issue is not described correctly, we have an even bigger problem:
```
((xmref_value==ref1,xmref_value==ref3),(xmref_value==ref3;(xmref_value==ref4,xmref_value==ref5)))
```
Is converted to: 
```
((xmref_value=in=(ref1,ref3);xmref_value==ref3),xmref_value=in=(ref4,ref5))
```
This is working as intended and produces:
xmref_value: (('label1' or 'label3') and ('label3') or ('label4' or 'label5')
Which matches what we expect, except from a missing ) in the end: (ref1 of 3) of (ref3 en (ref4 of 5))
Which gives 26 results

However, when we refresh, we get in the URL:
```
(xmref_value=in=(ref1,ref3),(xmref_value==ref3;xmref_value=in=(ref4,ref5)))
```
Which produces: 
 xmref_value: ('label1' or 'label3') or (('label3') and ('label4' or 'label5'))

Which gives 38 results

**Comment by marikaris** [comment]
Initially also broken in 4.1, but after the first refresh the query stays ok.

**Comment by marikaris** [comment]
When selecting complex query with and and or values, sometimes the or is undefined in the human readable view.
![screen shot 2017-10-24 at 16 38 01](https://user-images.githubusercontent.com/10075439/31949490-be5c5bcc-b8d9-11e7-8c6d-7206374cc1a8.png)
Sometimes it occurs, sometimes not, seems to be random.

**Comment by bartcharbon** [comment]
The query from the testplan is not really sensible (extra est of () and everything with "ref3" will match based on the first part of the query), however this also fails:
<your_molgenis>/menu/main/dataexplorer?entity=it_emx_datatypes_TypeTest&mod=data&filter=(xmref_value==ref1,xmref_value==ref2),(xmref_value==ref3;(xmref_value==ref4,xmref_value==ref5))
