### ISSUE TITLE
When I upload an EMX with a one_to_many in it, I get warning in unknown of validation

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6920]
### How to Reproduce
Upload 
[test_nillable_expression_questionnaire.xlsx](https://github.com/molgenis/molgenis/files/1478460/test_nillable_expression_questionnaire.xlsx)

### Expected behavior
Everything is green and ok

### Observed behavior
![screen shot 2017-11-15 at 09 28 16](https://user-images.githubusercontent.com/10075439/32827602-1239e650-c9ed-11e7-8c00-891fbdb4457d.png)
When proceeding, the attribute is however uploaded
![screen shot 2017-11-15 at 09 28 26](https://user-images.githubusercontent.com/10075439/32827629-22786848-c9ed-11e7-9e8a-0cf87235ffcb.png)
![screen shot 2017-11-15 at 09 28 35](https://user-images.githubusercontent.com/10075439/32827630-227a76c4-c9ed-11e7-9d92-2e3b830e44b7.png)

**Comment by dennishendriksen** [comment]
The warning is correct since bi-directional one-to-many attributes mapped by another attribute can only be imported through the owning side: one-to-many attribute 'books' of entity 'author' mapped by attribute 'author' of entity 'book' cannot be imported, only the owning attribute 'book' can be imported.
