### ISSUE TITLE
Internal server error when idAttribute of refEntity is visible == false and no other labelAttribute specified

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#6969]
### How to Reproduce
Create EMX model with one entity referencing to another, where idAttribute of the reference entity is set on visible == false (and no other attribute is specified as labelAttribute)

### Expected behavior
The importer will give a warning or error

### Observed behavior
The EMX is correctly uploaded, but you get an internal server error 500 when selecting the entity

-Marieke has an example if this is not clear enough ;-)

**Comment by fdlk** [comment]
Our own settings entity types do not adhere to this rule(!)

**Comment by marikaris** [comment]
I get 
<img width="607" alt="screen shot 2018-04-19 at 10 38 32" src="https://user-images.githubusercontent.com/10075439/38980802-14cec048-43be-11e8-9874-f2746c45f262.png">
when I try to upload:
[eric_meta_data.xlsx](https://github.com/molgenis/molgenis/files/1927304/eric_meta_data.xlsx)
This is because the age_unit table completely extents from the ontology_term table, but that table does have a labelAttribute, besides the invisible ID attribute

**Comment by bartcharbon** [comment]
https://github.com/molgenis/molgenis/pull/7322/files
