### ISSUE TITLE
I cannot submit my questions of the c6 questionnaire in the questionnaire plugin while I can in the dataexplorer

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6982]
### How to Reproduce
Import: 
[chr6 metadata](https://github.com/molgenis/molgenis/files/1530273/Chr6_vragen_emx_testimport_12_fix.xlsx)

and: 
[chr6 data](https://github.com/molgenis/molgenis/files/1530275/c6_questionnaire_2017-12-05_09_39_47.xlsx)

Go to the questionnaire plugin, submit

### Expected behavior
Item gets submit (as it does when switching status to submitted in dataexplorer and saving)

### Observed behavior
<img width="1252" alt="screen shot 2017-12-05 at 09 43 58" src="https://user-images.githubusercontent.com/10075439/33597832-dff2e1b0-d9a0-11e7-9ea7-616c19f03c9b.png">

**Comment by marikaris** [comment]
Same thing happens when I push the save button for an already submitted row without changing anything. 

![screen shot 2017-12-06 at 08 08 03](https://user-images.githubusercontent.com/10075439/33649154-05bb90d8-da5d-11e7-8528-240da1ceaff4.png)

**Comment by ConnorStroomberg** [comment]
The problem seems to be that:

Form.submit -> triggers -> JqueryFrom.submit -> triggers -> Questionare.js.beforeSubmit

this checks the 'visibleExpression' and if this is false, sets the value to null ( this causes the backend error). The visible expression uses the 'age' function. this 'age' function use a form value to calculate the dateOfBirth however the input for this age function is a string "1982-05-05". The age function can not handle a string ( is expects a date) and returns 'NaN'. As 'NaN' is falsy the Questionare.js.beforeSubmit function sets the value to null. 

To fix this we need to figure out why the date of birth is given as string instead of the expected date.
