### ISSUE TITLE
When having jobs running as superuser and my account is set to inactive, my jobs still run

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7169]
### How to Reproduce
Use RD connect app
Make super user account
Activate id card indexer
Log in as other super user
Make admin inactive (but keep it superuser)

### Expected behavior
Jobs fail, no read permissions on job execution

### Observed behavior
Jobs still succeed

**Comment by Mark-de-Haan** [comment]
I don't know, what is the expected behaviour?
@dennishendriksen How is this dealt with in new security?

**Comment by marikaris** [comment]
If a user is inactive, it should not be able to run jobs, you don't inactivate users without a reason.

**Comment by dennishendriksen** [comment]
> I don't know, what is the expected behaviour?
In my opinion:
- Jobs of inactive users can't be scheduled
- Deactivating a user cancels running jobs of that user

> @dennishendriksen How is this dealt with in new security?
Security functionality hasn't changed. Unrelated.

**Comment by LuukDijkhuis** [comment]
you don't create a recurring job without a reason either. There is a logic to having system level periodic jobs run in a security context that is not specifically tied to which administrator-level _person_ initiated it. See the "root" principle. It would be a continuity risk to have to reassign such jobs to someone else each time an admin person switches jobs. Possibly the "bug" is that this happens implicitly instead of an explicit "run this as admin" option.

**Comment by marikaris** [comment]
I don't expect jobs to be reassigned, I expect the correct user to submit these jobs and if that user is disabled, I have to recreate the job with another user in order for it to start again. The reason to disable the admin is that some people are not feeling comfortable with it because they don't know who "admin" is, so I can imagine running jobs by the disabled ghost admin they find even more scary   (although I think they won't be able to see that).

**Comment by LuukDijkhuis** [comment]
will be fixed by story #5676

**Comment by fdlk** [comment]
Fixed in #7278
