### ISSUE TITLE
Navigator view might not be up-to-date after import

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7178]
### How to Reproduce
Upload: 
[eric_de_model.xlsx](https://github.com/molgenis/molgenis/files/1730607/eric_de_model.xlsx)
Go to navigator

### Expected behavior
When I click on the package "eu_bbmri_eric_DE", I see the tables that are in there (collections, biobanks, networks and persons)
They are in the correct package:
<img width="1256" alt="screen shot 2018-02-16 at 09 33 03" src="https://user-images.githubusercontent.com/10075439/36299246-6fdbb768-12fc-11e8-963c-1c5050392ea9.png">

### Observed behavior
Nothing is in the package

**Comment by ConnorStroomberg** [comment]
When i try to reproduce, at first i to do not see the entities, when i  wait a bit and refresh the navigator the entities appear. I suspect this is due to the fact the index has not yet completed. 

If this is the case maybe we should only mark the import as completed when the indexing has finished, or maybe we should warn the user the indexing is not yet finished ( but this seems a bit low-level / technical to signal to the user).

**Comment by dennishendriksen** [comment]
@ConnorStroomberg FYI MOLGENIS used to warn users that indexing was still in progress. This was removed due to the message being too technical. Before that we kept the importer pending on indexing, but this was changed for performance reasons.

**Comment by dennishendriksen** [comment]
> I suspect this is due to the fact the index has not yet completed.

This is indeed the case. The query ```/api/v2/sys_md_EntityType?sort=label&num=1000&&q=isAbstract==false;package.id==eu_bbmri_eric_DE``` is not supported by PostgreSqlRepository due to package.id resulting in a nested query rule and will be forwarded to the index instead.

The correct version of this query ```/api/v2/sys_md_EntityType?sort=label&num=1000&&q=isAbstract==false;package==eu_bbmri_eric_DE``` is supported by PostgreSqlRepository and will resolve this isssue.
