### ISSUE TITLE
Setting a broken HREF for any of the frontend images will break the login redirect

### ISSUE THREAD

**Issue by cpavanrun** [molgenis/molgenis#7835]
### How to Reproduce
* Via Admin >> Settings >> **Logo in navigation bar** change the HREF from `/img/logo_molgenis_small.png` to `/foo/logo_molgenis_small.png`. The new value should result in a 403 (Access is denied) when queried directly.
* Logout
* Login

### Expected behavior
* Redirected to `http://localhost:8080`

### Observed behavior
* Redirected to `http://localhost:8080/foo/logo_molgenis_small.png` with a 302 (redirect) which will result in a 403 (Access is denied)
* Need to manually navigate to `http://localhost:8080` while keeping the login session.

We ran into this problem because we aproach the MolGenis instance both 
* via a _fqdn_
* via a ssh-tunnel (i.e. localhost:8080)

And one of the two breaks the custom HREF URIs to the images.

Tested on MolGenis 7.1.

Edit: spelling.

**Comment by dennishendriksen** [comment]
The following happens when navigating to ```http://localhost:8080/``` as an anonymous user:
1. Browser requests ```http://localhost:8080/foo/logo_molgenis_small.png```
2. Server checks whether the anonymous user can access this URL and decides access is denied
3. Server saves the request so it can return to the URL after successful login
4. Server returns a 302 to ```http://localhost:8080/login```
5. Browser requests ```http://localhost:8080/login```
6. Server returns 200 with login page content
7. Browser tries to render login page content as image but fails
8. User signs in using via the sign in button
9. Server returns 302 ```http://localhost:8080/foo/logo_molgenis_small.png```
10. Browser navigates to ```http://localhost:8080/foo/logo_molgenis_small.png```
11. User sees a ```HTTP Status 403 – Forbidden``` page
