### ISSUE TITLE
Large metadata manager checkboxes in ie11

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#8158]
### How to Reproduce
Open the metadata manger using ie11 and select a entity

### Expected behavior
![screenshot 2019-01-16 at 13 43 23](https://user-images.githubusercontent.com/1277621/51249816-c572cc80-1994-11e9-97e5-3be03aa335d3.png)

### Observed behavior
![big-check-boxes](https://user-images.githubusercontent.com/1277621/51249864-feab3c80-1994-11e9-8083-91e6e3cf89cc.PNG)

**Comment by dennishendriksen** [comment]
Similar issue in Chrome 72.0.3626.96:
![image](https://user-images.githubusercontent.com/2477186/52410539-e7b1c300-2ad8-11e9-8b8e-97fa46854c42.png)

**Comment by mswertz** [comment]
does this also occur in old style?

**Comment by MaxPostema** [comment]
I can't seem to be able to reproduce the issue on:

**Wom windows7 32bit**
IE 11.0.9600.19266
**Virtualbox windows7 32bit**
IE 11.0.9600.18860
Chrome 73.0.3683.86
**Virtualbox windows8.1 32bit**
IE 11.0.9600.18894

I did ones have a very similar issue that was caused by a CSS style collision with 1password.

**Comment by MaxPostema** [comment]
Issue comes from incorrect use of bootstrap. Radio buttons and checkboxes should not have the class `form-control`. 

( `form-control` is for 'Textual form controls' according to the bootstrap documentation )
