### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis#8194]
### How to Reproduce
Open documentation:
- Follow a file or a internal link to molgenis.gitbooks.io

Example:

On page:
https://molgenis.gitbooks.io/molgenis/content/quickstart/guide-quickstart.html 
> Importing your EMX file > upload guide

On page:
https://molgenis.gitbooks.io/molgenis/content/user_documentation/import-data/ref-emx.html
> Click a (download) button

### Expected behavior
File downloads 

### Observed behavior
Broken link / 404

**Comment by fdlk** [comment]
Link to upload docs is still broken. On gitbooks.io it links to `https://molgenis.gitbooks.io/molgenis/content/user_documentation/user_documentation/user_documentation/import-data/guide-upload`. 
On github it links to `https://github.com/molgenis/molgenis/blob/master/docs/user_documentation/import-data/guide-upload`

**Comment by marikaris** [comment]
@MaxPostema Fleur already fixed the quickstart link. The download links don't appear to be broken. They only work a bit quirky: you have to right click and open in new tab. That is a bit odd and user unfriendly but the links are not broken. 

There's also some other odd behavior: when clicking around and refreshing the page a lot, gitbook will ask for login rather than downloading. 

@mswertz I propose we look into this another time? I also would like to close this issue and create two new separate issues (because the links are not broken anymore): 
1) Documentation download links don't download on click
2) Gitbook asks for login after clicking around
