### ISSUE TITLE
Can not import data from BBMRI-Eric because of failing validation expressions

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis#8243]
### How to Reproduce
Download the live data of BBMRI-Eric:

```
java -jar downloader.jar -f bbmri_test.xlsx -u https://molgenis129.gcc.rug.nl/ eu_bbmri_eric_collections
```

The downloader can be downloaded here:

https://github.com/molgenis/molgenis-tools-emx-downloader/releases/download/v1.2/downloader.jar

### Expected behavior
Data is uploaded the right way.

### Observed behavior
Conversion failure in entity type [eu_bbmri_eric_collections] attribute [biobank_label]; No converter found capable of converting from type [org.molgenis.data.support.LazyEntity] to type [java.lang.String]

**Comment by dennishendriksen** [comment]
Caused by changes in 9eb856f3661181494e642166757bd3870e29802d that stopped allowing conversion from Entity to String in DataConverter.java (SoC) which breaks the 'xref as label attribute' trick.

The import succeeds when updating the data model to use the preferred template expressions:
```
{"template":"{{biobank.name}}"}
```

I propose to stop supporting this trick and update existing 8.0 data models to use template expressions.

**Comment by dennishendriksen** [comment]
By the way @sidohaakma: this issue is not related to validation expressions or expressions validated by a JavaScript engine.

**Comment by djvanenckevort** [comment]
For BBMRI-ERIC I would be in favour of updating the data model.
