### ISSUE TITLE
Broken layout of xref/mref labels in new molgenis style

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8353]
### How to Reproduce
Select an xref or mref value in the new form

### Expected behavior
If a pill is drawn around the selected value, it is visible and centered
OR, if no pill is drawn, the selected text is positioned just like in a string field
![Screenshot 2019-04-04 at 11 00 41](https://user-images.githubusercontent.com/1523838/55543222-ed86e780-56c8-11e9-96d6-d8452ba84b5b.png)

### Observed behavior
The pill is white and so is the background:
![Screenshot 2019-04-04 at 10 40 58](https://user-images.githubusercontent.com/1523838/55541878-2b364100-56c6-11e9-883f-a80a1770b5aa.png)

For mrefs it looks better (but the pill is still off-center):
![Screenshot 2019-04-04 at 10 54 41](https://user-images.githubusercontent.com/1523838/55542812-25d9f600-56c8-11e9-9484-5cdb52d80d11.png)

**Comment by connoratrug** [comment]
'fix' in https://github.com/molgenis/molgenis-ui-form/pull/272

real issue is [v-select](https://vue-multiselect.js.org/) does not really allow for theming you can hear the author of the library discuss this on the [views on vue podcast episode 56](https://devchat.tv/views-on-vue/vov-056-vue-components-news-platform-with-damian-dulisz/). 

He says  there are architectural issues that block theming the component in a nice way and he is working on a [v3 version](https://github.com/shentao/vue-multiselect/tree/v3/docs) to make this better. 

i propose to do minimal fixes as described in PR ( i going be hard to maintain) and switch to v3 when it is more stable.

**Comment by connoratrug** [comment]
[closed with 8.0 merge](https://github.com/molgenis/molgenis/commit/d9cfbc300855752a5854d35a460f882960722a1f)
