### ISSUE TITLE
i18n strings take 8-16 seconds to load (in the Data Explorer)

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#8618]
### How to Reproduce
1. In your browser, open up the Network tab of the inspector
2. Go to the Data Explorer

### Expected behavior
Data Explorer is relatively quick to load.

### Observed behavior
Data Explorer loads slow. The request to i18n takes a very long time (8 seconds locally, 16 seconds on master.dev)

**Comment by dennishendriksen** [comment]
```RestControllerV2.getL10nStrings``` performs a ```ResourceBundle.getString``` call for each ```sys_L10nString``` entity (~500 after a clean install) which leads to ~500 ```DataService.findOne``` calls, ~500 calls to retrieve the application language code which results in ~500 dataservice calls to retrieve the application settings.

An alternative to retrieve the same data in a different format is calling ```/api/v2/sys_L10nString?attrs=msgid,en&num=1000``` (optionally filtering on namespace). This requests completes near instantly.

Since REST API v2 is in the process of being replaced by Data API v3 it would make sense to discontinue using this endpoint. The suggested course of action is updating the JavaScript client to retrieve the data using the mentioned endpoint and transforming it to the response format getL10nStrings.

**Comment by connoratrug** [comment]
I can not reproduce, the reported findings, suggest to inspect further if problem persists.

**Comment by dennishendriksen** [comment]
@connoratrug how long did it take for the request to complete for you?

**Comment by connoratrug** [comment]
@dennishendriksen the whole page takes a few seconds depending if you are counting first render or load completed. Most of the request take around 300ms, one big outlier is 

http://localhost/api/v2/i18n?_=1567685484211

at 1.4 seconds

**Comment by dennishendriksen** [comment]
@connoratrug I can reproduce the issue, ```GET http://localhost/api/v2/i18n``` takes on average ~8.5s on my local machine.

**Comment by mswertz** [comment]
I couldn't reproduce in practice either, although I noticed laggyness. However, this architecture is CRAZY (sorry for the CAPS). 

I don't want to invest in data explorer 1.0. So is this also an issue in data explorer 2.0 and forms?
Because then I would want us to v3 which I understand will get all necessary i18n items in one/small number of calls?

**Comment by fdlk** [comment]
This only happens when the cache is warming, so if someone visited the page before you, you can no longer reproduce.

**Comment by dennishendriksen** [comment]
@fdlk I can reproduce the problem multiple times without restarting MOLGENIS (hence the average timings).

**Comment by fdlk** [comment]
The spring MessageSource that is being used for all i18n relies on the dataservice for caching, so if the localization table has outgrown the default cache size we need to extend it just like we did for the metadata.
You won't just run into this problem in the api/v2 but everywhere, e.g. in exception translation and in freemarker

**Comment by dennishendriksen** [comment]
Please read my previous comment: the current implementation is fundamentally flawed since it doesn't scale with the number of entities in the table. Please stop using the endpoint and retrieve the data using the suggested endpoint which should be an easy fix in the js client.
