### ISSUE TITLE
Serving the home page generates too many transactions

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8692]
### How to Reproduce
In the log manager, add a debug logger for `org.molgenis.data.index`
Curl the home page of the server (no browser, just the html of the home page)
Count the amount of transactions generated by the call

### Expected behavior
Just one, maybe three transactions.

### Observed behavior
I think I see about 20 of them

**Comment by dennishendriksen** [comment]
PR #8699 (that fixes #8695) is an improvement for this issue. Navigating to the home page as an anonymous user results in the following read-only transactions:
```
7 LocalizationMessageSource.resolveCodeWithoutArguments
5 UserLocaleResolverImpl.resolveLocale
1 MolgenisInterceptor.posthandle
1 MolgenisMenuController.forwardDefaultMenuDefaultPlugin
1 HomeController.init
1 PluginInterceptor.postHandle
```

### 5 UserLocaleResolverImpl.resolveLocale
1) render forward:/menu
2) render forward:/plugin/home
3) MolgenisInterceptor.postHandle --> put i18n in model
4) render forward:/plugin/view-staticcontent
5) spring puts locale in model (because exposeSpringMacroHelpers=true)

### 7 LocalizationMessageSource.resolveCodeWithoutArguments
Requests initiated during rendering of view-staticcontent.ftl

### Others
Expected

Requesting the home page with the fix included takes about ~125ms
