### ISSUE TITLE
Help docs code example formatting broken in permission docs

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis#8772]
### How to Reproduce
go to: https://molgenis.gitbooks.io/molgenis/content/guide-api-permissions.html
- scroll down to detail section on using the api to change permissions

### Expected behavior
nice formatting of code example, similar to elsewhere in the docs

### Observed behavior
formatted, hard to read json string  json string

**Comment by dennishendriksen** [comment]
Workaround: use https://github.com/molgenis/molgenis/blob/master/docs/guide-api-permissions.md instead of the gitbooks documentation.

I can't spot any errors in the markdown file that would lead to the rendering errors on gitbook.

**Comment by dennishendriksen** [comment]
Related:  http://wiki.gcc.rug.nl/ticket/6666

**Comment by mswertz** [comment]
why are we still using gitbook? I have refactored the lot into vuedocs.

**Comment by dennishendriksen** [comment]
@sidohaakma could you address @mswertz his question?

**Comment by sidohaakma** [comment]
@mswertz: At that time we split the story into to parts. The refactoring of the docs, which is merged into the master months ago and the transition to vuepress (https://github.com/molgenis/molgenis/pull/8491/ needs to be merged with master still). This is not merged into the master yet because of lack of time at that point. We needed to do some work regarding old versions of the documentation as well. This PR only enabled us to deploy the latest docs on docs.molgenis.org or something like that.

**Comment by tommydeboer** [comment]
Here in 2021 it looks good: https://molgenis.gitbook.io/molgenis/interoperability/guide-api-permissions

There were some `json` tags missing though, which I've added in https://github.com/molgenis/molgenis/pull/9349 (among other things).
